### ISSUE TITLE
Gradient background applicable?

### ISSUE THREAD

**Issue by Danjavia** [jfilter/react-native-onboarding-swiper#19]
Hi, first of all, Amazing component, great job!

I want to know if is possible to set the backgroundColor with gradient as LinearGradient?

**Comment by jfilter** [comment]
You want to use https://github.com/react-native-community/react-native-linear-gradient for setting the background? Hmm, I will not add it as dependency (because it requires linking native code). 

Maybe one could create a prop that replaces this [animated view component](https://github.com/jfilter/react-native-onboarding-swiper/blob/master/src/index.js#L138) with an own component. I will not do it but if you want to do it, feel free to send a PR. ;)

**Comment by jfilter** [comment]
I am closing this for now. If somebody has a way to do this in JS only, please send a PR.

**Comment by Michaelvons** [comment]
Thanks to React 0.60 and greater, linking is no longer required. Kindly add it to your package. it will be super useful !!. Thanks
