### ISSUE TITLE
Display horizontal scrolling

### ISSUE THREAD

**Issue by ritz078** [jfilter/react-native-onboarding-swiper#22]
I want to disable horizontal scrolling until a certain action has been completed. Maybe a prop to disable horizontal scrolling that also hides the next button will be helpful.

**Comment by jfilter** [comment]
There is the prop `flatlistProps` which gives props directly to the flat list. So you can disable scrolling with `flatlistProps={{scrollEnabled: False}}`. Does it solve your need?

**Comment by ritz078** [comment]
yes, it does. Thanks. 👍

**Comment by ritz078** [comment]
but he will still be able to drag and slide. right? And if we disable scroll, we are disabling the previous scroll too.

We have to lazily load next slides in that case.

**Comment by jfilter** [comment]
Yes, maybe you can even do it with the current version. FlatList has a prop called `extraData` to dynamically add new items. A page is in our case one item. So instead of giving all pages upfront with the `pages` prop, you have to give them via the `flatlistProps`. Maybe you also have to change some other stuff in https://github.com/jfilter/react-native-onboarding-swiper/blob/master/src/index.js. I am not sure right now.
