### ISSUE TITLE
Swipper Responsive Problem

### ISSUE THREAD

**Issue by BalaRajendran** [jfilter/react-native-onboarding-swiper#73]
Hii, I tired this package in my package. The image is not responsive to all android versions.  The title and subtitles are hidden in lower android versions. Can you please tell how to make responsive this package? 
See this Screenshots
![WhatsApp Image 2019-11-09 at 7 30 54 AM](https://user-images.githubusercontent.com/31990008/68521050-1c9ab280-02c3-11ea-95e6-a75ae4a6693b.jpeg)

![WhatsApp Image 2019-11-09 at 7 31 15 AM](https://user-images.githubusercontent.com/31990008/68521036-f83ed600-02c2-11ea-8636-42b4a29e634b.jpeg)

**Comment by lrpinto** [comment]
Hi Bala,

I am not a author of this library, just a user like you and trying to help.

The issue you report also happens when running  the Demo App "react-native-onboarding-swiper – simple example" (https://snack.expo.io/rk80s-CDz) in a Android Nexus 5.

For the particular Image components, the bitmaps of 250x250 are too large and cause the Subtitle and Title to be past the bottom of the screen. 

The solution could be to provide different assets for different screen densities. This means creating similar image files of different sizes. 

For example, resize circle.png to 64x64, 128x128 and 192x192. You should end with the following files. Please note how the files are named.

![circle@3x](https://user-images.githubusercontent.com/2735779/72003734-e5546d80-3241-11ea-850a-108771c6ce0a.png)
![circle](https://user-images.githubusercontent.com/2735779/72003735-e5546d80-3241-11ea-8af4-a5c9d57df51a.png)
![circle@2x](https://user-images.githubusercontent.com/2735779/72003736-e5546d80-3241-11ea-9e5d-81a33c0c1eda.png)

For more details see,
- https://developer.android.com/training/multiscreen/screendensities.
- https://docs.expo.io/versions/latest/react-native/images/

Another option might be to use SVG graphics that scaled nicely instead of bitmaps in your Image components.

**Comment by lrpinto** [comment]
Hi Bala,

I had a closer look this. Styles can also be overridden with Flexbox.

For example,

```
const styles = StyleSheet.create({
	containerStyles: {
		backgroundColor: 'yellow',
		flex: 1,
		flexDirection: 'column',
		justifyContent: 'flex-start',
		alignItems: 'center',
		marginTop: 0,
		marginBottom: 0,
		paddingBottom: 0,
		paddingTop: 0
	},
	imageContainerStyles: {
		backgroundColor: 'green',
		flex: 0,
		alignItems: 'center',
		width: '100%',
		marginTop: 0,
		marginBottom: 0,
		paddingBottom: 16,
		paddingTop: 16
	},
	titleStyles: {
		backgroundColor: 'red'
	},
	subTitleStyles: {
		backgroundColor: 'pink'
	}
})
```

Then on the component

```
              <Onboarding
			containerStyles={styles.containerStyles}
			imageContainerStyles={styles.imageContainerStyles}
			titleStyles={styles.titleStyles}
			subTitleStyles={styles.subTitleStyles}
                        ...
		/>
```

Would fix the issue of title and subtitle hidden on a Nexus 5 (background colors are just for reference).

![image](https://user-images.githubusercontent.com/2735779/72010868-93ffaa80-3250-11ea-9622-71fd8410dae9.png)


References
- https://facebook.github.io/react-native/docs/flexbox

**Comment by BalaRajendran** [comment]
Thank You for your response
